### ISSUE TITLE
BangPy创建nram类型Buffer存在问题

### ISSUE THREAD

**Issue by MasterJianxing** [Cambricon/mlu-ops#37]
之前也曾遇到过这种问题，后来确认过一次应该是shape内部出了问题。
这次仍然遇到了这个问题，非常不理解，想要获得解决方案。
`with self.bp.if_scope(dim == 0):
            dim_h = 1
            dim_m = self.dim_0
            dim_l = self.dim_1 * self.dim_2 * self.dim_3   
            buffer_out = self.bp.Buffer(
                shape=(dim_h, 1, dim_l), name="OUTPUT", dtype=self.dtype, scope="global"
            )`
这里在编译的时候是通过的。但后面的创建nram部分就出错了。
`buffer_out_n = self.bp.Buffer(
                shape=(dim_h, 1, dim_l),
                name="OUTN",
                dtype=self.dtype,
                scope="nram",
            )`
会被报错。报错情况如下
Build all operators...
Traceback (most recent call last):
  File "/home/pan/mlu-ops/bangpy-ops/utils/build_and_test_all_operators.py", line 145, in <module>
    main()
  File "/home/pan/mlu-ops/bangpy-ops/utils/build_and_test_all_operators.py", line 127, in main
    build_all_op()
  File "/home/pan/mlu-ops/bangpy-ops/utils/build_and_test_all_operators.py", line 65, in build_all_op
    obj(None, None)
  File "/usr/local/lib/python3.8/site-packages/bangpy/tcp/tcp.py", line 529, in wrapper
    mod = f(type_, target_)
  File "/home/pan/mlu-ops/bangpy-ops/ops/cosine_similarity/cosine_similarity.py", line 487, in build_cosine_similarity
    f = Cosine_similarity(dtype, target, task_num, stage).compute_body()
  File "/home/pan/mlu-ops/bangpy-ops/ops/cosine_similarity/cosine_similarity.py", line 106, in compute_body
    buffer_out_n = self.bp.Buffer(
  File "/usr/local/lib/python3.8/site-packages/bangpy/tcp/tcp.py", line 178, in Buffer
    Check.nocheck("Cannot handle this data type", TypeError)
  File "/usr/local/lib/python3.8/site-packages/bangpy/tools/check.py", line 47, in nocheck
    print_error_msg(error_message, exception_type)
  File "/usr/local/lib/python3.8/site-packages/bangpy/tools/traceback.py", line 131, in print_error_msg
    raise exception_type(debug_info)
ValueError: [ET000] Cannot handle this data type
 62        print("======================")
 63        print("Build all operators...")
 64        for obj in build_entrys:
 65 -->        obj(None, None)`
之前说是因为控制流的问题，就是if_scope后面没有memcpy操作。但是这次，我每个条件下后面都有memcpy操作，但还是出了问题，想知道问题原因以及如何解决。

**Comment by zhangyicole** [comment]
看起来在定义nram scope上的shape时没有使用固定形状，使用了可变var来定义形状？请使用固定值形状(int常量)来定义nram scope buffer的形状。

**Comment by MasterJianxing** [comment]
我的self.dim_0/1/2/3都是在init中定义的sizevar变量，作为输入数据的初始维度信息，这也不能直接使用吗。那如果不能使用的话，我应该怎么在nram里声明一块这么大的空间呢

**Comment by SYangDong** [comment]
你可以看看nram的size， 只要不超过就行。可以看看samples里面是怎么用的

**Comment by WangYuan-cn** [comment]
@MasterJianxing  该问题是否已解决？

**Comment by MasterJianxing** [comment]
已解决
